# =============================== #
# Autogenerated file, do not edit #
# =============================== #
import os
from sqlalchemy import create_engine

import data_model

from sqlalchemy.orm import declarative_base
from sqlalchemy_utils import database_exists, create_database, drop_database

Base = declarative_base()
UID = os.environ["POSTGRES_USER"]
PWD = os.environ["POSTGRES_PASSWORD"]
DBNAME = os.environ["POSTGRES_DB"]

engine = create_engine(f"postgresql+psycopg2://{UID}:{PWD}@opencdms-database:5432/{DBNAME}")

if database_exists(engine.url):
    drop_database(engine.url)

create_database(engine.url)
Base.metadata.create_all(engine)
